; OpenSmartFocuser — PlatformIO Configuration
; https://docs.platformio.org/page/projectconf.html

[env:default]
platform = atmelavr         ; Update to match your MCU
board = uno                 ; Update to match your board
framework = arduino

lib_deps =
    ; Add library dependencies here

build_flags =
    -D VERSION=\"0.1.0\"
